import { forwardRef } from 'react'
import './about.css'

const About = forwardRef((props, ref) => {
    return <section ref={ref} className="about-section">
        <h2>ABOUT</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore amet corporis perspiciatis, mollitia soluta ipsum unde, a saepe quae, cupiditate facilis veniam vitae alias eos officia perferendis porro omnis eum architecto error qui cumque magni. Voluptas dolorem facilis quae quod sit. Voluptatem molestias quidem totam tempore. Voluptatem nulla id pariatur quod soluta praesentium minima explicabo assumenda minus mollitia repudiandae nesciunt, tempora esse, molestiae repellat aspernatur suscipit cum exercitationem accusamus consectetur dolorem magni quo inventore tempore? Architecto placeat porro expedita omnis, laudantium dolore! Nulla eum mollitia reprehenderit enim nam necessitatibus molestias distinctio inventore accusantium impedit. Libero harum voluptate voluptatibus ab provident, magnam corrupti est quae minus, doloribus earum fuga ipsam natus quas possimus eos ut nostrum, nulla sunt labore modi quod? Earum rerum quo dolor, odio sed culpa error. Itaque sint quaerat harum reprehenderit iusto ducimus quas nulla atque ea dolores temporibus neque voluptatum voluptate nostrum quisquam cumque aliquam ab, dolor sunt tenetur soluta voluptatibus voluptatem repellendus illo. Doloremque eveniet amet, iste inventore modi cum vitae expedita doloribus nemo magnam voluptatibus placeat commodi, necessitatibus distinctio, quo ad dicta! Numquam beatae illo ipsam sequi aut! Illo voluptas rem vero, optio veritatis magni, magnam inventore dolorem deleniti architecto earum laborum? Beatae, enim eaque.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea magnam voluptatum ab pariatur doloribus repellendus, corrupti ullam excepturi commodi sed veritatis ipsa quidem voluptatibus eos quas? Eum voluptates eius natus est expedita, qui nemo tenetur, consequatur vero magnam aspernatur debitis repellat. Nisi voluptas autem quisquam distinctio iure incidunt quam aliquam dolores veritatis pariatur provident saepe necessitatibus minima, explicabo quasi, neque eum. Repellendus veniam itaque sint modi aliquam sequi, at corrupti, inventore dolores animi officia eligendi illo ea fuga iste libero voluptatibus error magnam, aperiam iusto. Inventore laboriosam voluptate dolor deleniti hic, qui modi sunt sapiente corrupti quaerat. Maiores tempora, perferendis quae inventore reprehenderit repellat. Atque, quidem quia nesciunt pariatur nihil ipsam veritatis, exercitationem enim cumque natus vel itaque magni! Repellat dolorem recusandae sapiente porro iste iusto beatae esse obcaecati mollitia quaerat? Impedit nulla quia laboriosam quasi placeat repellat! Minima eligendi dolorum quaerat quae debitis assumenda explicabo sequi, similique, consequuntur corporis consectetur, facilis labore soluta repudiandae vitae? Est, soluta ipsam, fugit esse dignissimos praesentium iste facilis tempore dolor recusandae itaque sunt officiis illum quos totam iure doloribus provident voluptatem adipisci dolorum vel cum? Magni magnam, laboriosam illo odit earum facilis sed nobis placeat esse rerum nisi iusto molestiae hic, ab corporis.</p>
    </section>
})

export default About;